# Jets::Config.project_namespace is special value results in using the project namespace. Example :
# table_namespace: <%= Jets.config.project_namespace %>
# This is the default value.

development:
  table_namespace: <%= Jets.config.table_namespace %>
  # More examples:
  # table_namespace: demo-dev

  # DynamoDB를 이용하기 위한 엔드포인트 ( 모두 동일 )
  endpoint: http://dynamodb.ap-northeast-2.amazonaws.com # comment out if want to test with real dynamodb
  # on AWS. You can also set the DYNAMODB_ENDPOINT environment variable.
  # You can also are actually deploying a development environment is to
  # change bin/server and export DYNAMODB_ENDPOINT=http://localhost:8000 at the top
  # there.

test:
  # table_namespace: proj # do not include the env
  endpoint: http://localhost:8000
  table_namespace: <%= Jets.config.table_namespace %>

production:
  table_namespace: <%= Jets.config.table_namespace %>
  endpoint: http://dynamodb.ap-northeast-2.amazonaws.com
